version: 0.0
os: linux
files:
 - source: .
   destination: /data/datacollector
permissions:
#  group = wheel  and mode = 564 (dr-xrw-r--).
 - object: /data/datacollector/getdata.sh
   group: root
   mode: 777
   type:
     - file
 - object: /data/datacollector/getdata_test.sh
   group: root
   mode: 777
   type:
     - file     
 - object: /data/datacollector/install_dependencies.sh
   group: root
   mode: 564
   type:
     - file
hooks:
  BeforeInstall:
    - location: scripts/fetch_env.sh
      timeout: 300
      runas: ec2-user
 AfterInstall:
   - location: install_dependencies.sh
     runas: root
