version: 0.0
os: linux
files:
 - source: .
   destination: /data/datacollector
permissions:
#  group = wheel and mode = 564 (dr-xrw-r--).
 - object: /data/datacollector/getdata.sh
   group: root
   mode: 564
   type:
     - file
