mode: prod

mongo_host: 127.0.0.1
mongo_db: 'active_digital'
mongo_port: 27017

funding_payments: &funding_payments
  function: funding_payments.py
  scheduler: [continuous,external,5 4 * * *]
  base_ccy: USDT

balances: &balances
  function: balance.py
  scheduler: [continuous,external,5 4 * * * ]
  base_ccy: USDT
  store_type: timeseries

symbols:
  symbols_1: &symbols_1 ['BTC', 'ETH', 'USDT', 'XRP', 'BNB', 'DOGE', 'SOL', 'LTC', 'BCH', 'DOT', 'ARB', 'ADA', 'OP', 'SUI', 'APT', 'EOS', 
    'ECT', FIL', 'DYDX', 'ATOM', 'APE', 'CRV', 'TRX', 'RUNE', 'UNI', 'GALA', 'NEAR', '1000PEPE', 'PEPE', 'XMR', 'SAND', 'AAVE', 'USDC', 'AXS', 
    'COMP', 'GMT', 'ICP', 'MANA', 'ALGO', 'SHIB', 'SUSHI', 'GRT', '1INCH', 'CHZ', 'NEO', 'KNC', 'XTZ', 'THETA', 
    'DASH', 'PEOPLE', 'LRC', 'ZIL', 'OMG', 'ROSE', 'AR', 'COTI', 'ICX', ]
  symbols_2: &symbols_2 ['BTC/USDT', 'ETH/USDT', 'USDT/USDT', 'XRP/USDT', 'BNB/USDT', 'DOGE/USDT', 'SOL/USDT', 'LTC/USDT', 'BCH/USDT', 'DOT/USDT', 'ARB/USDT', 'ADA/USDT', 'OP/USDT', 'SUI/USDT', 'APT/USDT', 'EOS/USDT', 
    'ECT/USDT', FIL/USDT', 'DYDX/USDT', 'ATOM/USDT', 'APE/USDT', 'CRV/USDT', 'TRX/USDT', 'RUNE/USDT', 'UNI/USDT', 'GALA/USDT', 'NEAR/USDT', '1000PEPE/USDT', 'PEPE/USDT', 'XMR/USDT', 'SAND/USDT', 'AAVE/USDT', 'USDC/USDT', 'AXS/USDT', 
    'COMP/USDT', 'GMT/USDT', 'ICP/USDT', 'MANA/USDT', 'ALGO/USDT', 'SHIB/USDT', 'SUSHI/USDT', 'GRT/USDT', '1INCH/USDT', 'CHZ/USDT', 'NEO/USDT', 'KNC/USDT', 'XTZ/USDT', 'THETA/USDT', 
    'DASH/USDT', 'PEOPLE/USDT', 'LRC/USDT', 'ZIL/USDT', 'OMG/USDT', 'ROSE/USDT', 'AR/USDT', 'COTI/USDT', 'ICX/USDT', ]
  symbols_3: &symbols_3 ['BTC/USDT:USDT', 'ETH/USDT:USDT', 'USDT/USDT:USDT', 'XRP/USDT:USDT', 'BNB/USDT:USDT', 'DOGE/USDT:USDT', 'SOL/USDT:USDT', 'LTC/USDT:USDT', 'BCH/USDT:USDT', 'DOT/USDT:USDT', 'ARB/USDT:USDT', 'ADA/USDT:USDT', 'OP/USDT:USDT', 'SUI/USDT:USDT', 'APT/USDT:USDT', 'EOS/USDT:USDT', 
    'ECT/USDT:USDT', FIL/USDT:USDT', 'DYDX/USDT:USDT', 'ATOM/USDT:USDT', 'APE/USDT:USDT', 'CRV/USDT:USDT', 'TRX/USDT:USDT', 'RUNE/USDT:USDT', 'UNI/USDT:USDT', 'GALA/USDT:USDT', 'NEAR/USDT:USDT', '1000PEPE/USDT:USDT', 'PEPE/USDT:USDT', 'XMR/USDT:USDT', 'SAND/USDT:USDT', 'AAVE/USDT:USDT', 'USDC/USDT:USDT', 'AXS/USDT:USDT', 
    'COMP/USDT:USDT', 'GMT/USDT:USDT', 'ICP/USDT:USDT', 'MANA/USDT:USDT', 'ALGO/USDT:USDT', 'SHIB/USDT:USDT', 'SUSHI/USDT:USDT', 'GRT/USDT:USDT', '1INCH/USDT:USDT', 'CHZ/USDT:USDT', 'NEO/USDT:USDT', 'KNC/USDT:USDT', 'XTZ/USDT:USDT', 'THETA/USDT:USDT', 
    'DASH/USDT:USDT', 'PEOPLE/USDT:USDT', 'LRC/USDT:USDT', 'ZIL/USDT:USDT', 'OMG/USDT:USDT', 'ROSE/USDT:USDT', 'AR/USDT:USDT', 'COTI/USDT:USDT', 'ICX/USDT:USDT', ]
  symbols_4: &symbols_4 ['BTCUSD_PERP', 'ETHUSD_PERP', 'USDTUSD_PERP', 'XRPUSD_PERP', 'BNBUSD_PERP', 'DOGEUSD_PERP', 'SOLUSD_PERP', 'LTCUSD_PERP', 'BCHUSD_PERP', 'DOTUSD_PERP', 'ARBUSD_PERP', 'ADAUSD_PERP', 'OPUSD_PERP', 'SUIUSD_PERP', 'APTUSD_PERP', 'EOSUSD_PERP', 
    'ECTUSD_PERP', FILUSD_PERP', 'DYDXUSD_PERP', 'ATOMUSD_PERP', 'APEUSD_PERP', 'CRVUSD_PERP', 'TRXUSD_PERP', 'RUNEUSD_PERP', 'UNIUSD_PERP', 'GALAUSD_PERP', 'NEARUSD_PERP', '1000PEPEUSD_PERP', 'PEPEUSD_PERP', 'XMRUSD_PERP', 'SANDUSD_PERP', 'AAVEUSD_PERP', 'USDCUSD_PERP', 'AXSUSD_PERP', 
    'COMPUSD_PERP', 'GMTUSD_PERP', 'ICPUSD_PERP', 'MANAUSD_PERP', 'ALGOUSD_PERP', 'SHIBUSD_PERP', 'SUSHIUSD_PERP', 'GRTUSD_PERP', '1INCHUSD_PERP', 'CHZUSD_PERP', 'NEOUSD_PERP', 'KNCUSD_PERP', 'XTZUSD_PERP', 'THETAUSD_PERP', 
    'DASHUSD_PERP', 'PEOPLEUSD_PERP', 'LRCUSD_PERP', 'ZILUSD_PERP', 'OMGUSD_PERP', 'ROSEUSD_PERP', 'ARUSD_PERP', 'COTIUSD_PERP', 'ICXUSD_PERP', ]

instruments: 
  store_type: snapshot

positions:
  store_type: timeseries
  margin_mode: non_portfolio

tickers:
  symbols: *symbols_2
  store_type: timeseries

leverages:
  store_type: timeseries

transactions:
  store_type: timeseries
  fetch_type: time # time, id

fills:
  store_type: timeseries
  fetch_type: time # time, id

  symbols:
    binance: ['BTCUSDT',]
    okx: ['BTC-USDT-SWAP',]

mark_prices:
  store_type: timeseries

bid_ask:
  spot: *symbols_2
  perp: *symbols_3

borrow_rates:
  period: interval # yearly, daily or interval

  codes: *symbols_1



funding_rates:
  bybit:
    helper: bybithelper.py
    instruments:  
      ["BTC.USDT.PERP","ETH.USDT.PERP"]
  binance:
    helper: binancehelper.py
    instruments:  
      ["BTC.USDT.PERP","ETH.USDT.PERP"]
  okx:
    helper: okxhelper.py
    instruments:  
      ["BTC.USDT.PERP","ETH.USDT.PERP"]

  period: interval

  symbols: 
    binance_f: *symbols_3
    binance_d: *symbols_4
    okx: *symbols_3

clients:
  deepspace:
    bybit_subaccount1: &bybit_subaccount1
      apikey: xyz
      apisecret: zyx
    binance_subaccount1: &binance_subaccount1
      apikey: xyz
      apisecret: xyz
    binance_subaccount2: &binance_subaccount2
      apikey: xyz
      apisecret: xyz
    okx_subaccount1: &okx_subaccount1
      apikey: zyx
      apisecret: xyz
    okx_subaccount2: &okx_subaccount2
      apikey: zyx
      apisecret: xyz
    
    funding_payments:
      bybit:
        <<: *funding_payments
        helper: bybithelper.py
        subaccount1: *bybit_subaccount1
      binance:
        <<: *funding_payments
        helper: binancehelper.py
        subaccount1: *binance_subaccount1
        subaccount2: *binance_subaccount2
      okx:
        <<: *funding_payments
        helper: okxhelper.py
        subaccount1: *okx_subaccount1

    balances:    
      function: balance.py
      scheduler: [continuous,external,5 4 * * * ]
      bybit:
        <<: *balances
        helper: bybithelper.py
        subaccount1: *bybit_subaccount1
      binance:
        <<: *balances
        helper: binancehelper.py
        subaccount1: *binance_subaccount1
        subaccount2: *binance_subaccount2
      okx:
        <<: *balances
        helper: okxhelper.py
        subaccount1: *okx_subaccount1

  highsky:  
    funding_payments:
      bybit:
        <<: *funding_payments
        helper: bybithelper.py
        subaccount1: *bybit_subaccount1
      binance:
        <<: *funding_payments
        helper: binancehelper.py
        subaccount1: *binance_subaccount1
        subaccount2: *binance_subaccount2
      okx:
        <<: *funding_payments
        helper: okxhelper.py
        subaccount1: *okx_subaccount1

    balances:    
      function: balance.py
      scheduler: [continuous,external,5 4 * * * ]
      bybit:
        <<: *balances
        helper: bybithelper.py
        subaccount1: *bybit_subaccount1
      binance:
        <<: *balances
        helper: binancehelper.py
        subaccount1: *binance_subaccount1
        subaccount2: *binance_subaccount2
      okx:
        <<: *balances
        helper: okxhelper.py
        subaccount1: *okx_subaccount1

  besttrader:  
    funding_payments:
      bybit:
        <<: *funding_payments
        helper: bybithelper.py
        subaccount1: *bybit_subaccount1
      binance:
        <<: *funding_payments
        helper: binancehelper.py
        subaccount1: *binance_subaccount1
      okx:
        <<: *funding_payments
        helper: okxhelper.py
        sub1ap: *okx_subaccount1
        sub2aa: *okx_subaccount2

    balances:    
      function: balance.py
      scheduler: [continuous,external,5 4 * * * ]
      bybit:
        <<: *balances
        helper: bybithelper.py
        subaccount1: *bybit_subaccount1
      binance:
        <<: *balances
        helper: binancehelper.py
        subaccount1: *binance_subaccount1
      okx:
        <<: *balances
        helper: okxhelper.py
        sub1ap: *okx_subaccount1
        sub2aa: *okx_subaccount2

  jess:
    okx_submn: &okx_submn
      apikey: zyx
      apisecret: xyz

    funding_payments:
      okx:
        <<: *funding_payments
        helper: okxhelper.py
        subandyactivedigital: *okx_submn
        subandypants: *okx_submn
        subjessetf: *okx_submn
        subadtest2: *okx_submn

    balances:
      function: balance.py
      scheduler: [continuous,external,5 4 * * * ]
      okx:
        <<: *balances
        helper: okxhelper.py
        subandyactivedigital: *okx_submn
        subandypants: *okx_submn
        subjessetf: *okx_submn
        subadtest2: *okx_submn

