mode: prod

mongo_host: 127.0.0.1
mongo_db: 'active_digital'
mongo_port: 27017

funding_payments: &funding_payments
  function: funding_payments.py
  scheduler: [continuous,external,5 4 * * *]
  base_ccy: USDT

balances: &balances
  function: balance.py
  scheduler: [continuous,external,5 4 * * * ]
  base_ccy: USDT
  store_type: timeseries

instruments: 
  store_type: snapshot

positions:
  store_type: timeseries
  margin_mode: non_portfolio

tickers:
  symbols: ['BTC/USDT', ]
  store_type: timeseries

leverages:
  store_type: timeseries

transactions:
  store_type: timeseries
  fetch_type: time # time, id

fills:
  store_type: timeseries
  fetch_type: time # time, id
  symbols:
    binance: ['BTCUSDT',]
    okx: ['BTC-USDT-SWAP',]

mark_prices:
  store_type: timeseries

borrow_rates:
  codes: ['BTC', 'ETH', 'USDT', ]

bid_ask:
  spot: ['BTC/USDT', 'ETH/USDT', ]
  perp: ['BTC/USDT:USDT', 'ETH/USDT:USDT', ]

funding_rates:
  bybit:
    helper: bybithelper.py
    instruments:  
      ["BTC.USDT.PERP","ETH.USDT.PERP"]
  binance:
    helper: binancehelper.py
    instruments:  
      ["BTC.USDT.PERP","ETH.USDT.PERP"]
  okx:
    helper: okxhelper.py
    instruments:  
      ["BTC.USDT.PERP","ETH.USDT.PERP"]

  symbols: 
    binance_f: ['BTC/USDT:USDT', 'ETH/USDT:USDT', 'XRP/USDT:USDT', 'SOL/USDT:USDT', 'LTC/USDT:USDT', 
      'OP/USDT:USDT', 'SUI/USDT:USDT', 'TRX/USDT:USDT', 'UNI/USDT:USDT', 'RUNE/USDT:USDT', 
      'XMR/USDT:USDT', 'SAND/USDT:USDT', 'USDC/USDT:USDT', 'MANA/USDT:USDT', 'SUSHI/USDT:USDT', 'NEO/USDT:USDT', 
      'XTZ/USDT:USDT', 'THETA/USDT:USDT', 'PEOPLE/USDT:USDT', 'LRC/USDT:USDT', 'OMG/USDT:USDT', 'ICX/USDT:USDT', 
      'NEAR/USDT:USDT', 'DASH/USDT:USDT', 'BNB/USDT:USDT', 'DOGE/USDT:USDT', 'BCH/USDT:USDT', 'DOT/USDT:USDT', 
      'ARB/USDT:USDT', 'ADA/USDT:USDT', 'APT/USDT:USDT', 'EOS/USDT:USDT', 'GMT/USDT:USDT', 'FIL/USDT:USDT', 'DYDX/USDT:USDT', 
      'ATOM/USDT:USDT', 'APE/USDT:USDT', 'CRV/USDT:USDT', 'GALA/USDT:USDT', 'AAVE/USDT:USDT', 'AXS/USDT:USDT', 
      'COMP/USDT:USDT', 'ICP/USDT:USDT', 'ALGO/USDT:USDT', 'GRT/USDT:USDT', '1INCH/USDT:USDT', 'CHZ/USDT:USDT', 
      'KNC/USDT:USDT', 'ZIL/USDT:USDT', 'AR/USDT:USDT', 'ROSE/USDT:USDT', '1000PEPE/USDT:USDT', ]

    binance_d: ['BTCUSD_PERP', 'ETHUSD_PERP', 'XRPUSD_PERP', 'SOLUSD_PERP', 'LTCUSD_PERP', 
      'OPUSD_PERP', 'TRXUSD_PERP', 'UNIUSD_PERP', 'RUNEUSD_PERP', 
      'XMRUSD_PERP', 'SANDUSD_PERP', 'MANAUSD_PERP', 'XTZUSD_PERP', 'THETAUSD_PERP', 'ICXUSD_PERP', 
      'NEARUSD_PERP', 'BNBUSD_PERP', 'DOGEUSD_PERP', 'BCHUSD_PERP', 'DOTUSD_PERP', 
      'ADAUSD_PERP', 'APTUSD_PERP', 'EOSUSD_PERP', 'GMTUSD_PERP', 'FILUSD_PERP', 
      'ATOMUSD_PERP', 'APEUSD_PERP', 'CRVUSD_PERP', 'GALAUSD_PERP', 'AAVEUSD_PERP', 'AXSUSD_PERP', 
      'ALGOUSD_PERP', 'CHZUSD_PERP', 'KNCUSD_PERP', 'ZILUSD_PERP', 'ROSEUSD_PERP', ]

    okx: ['BTC/USDT:USDT', 'ETH/USDT:USDT', 'XRP/USDT:USDT', 'SOL/USDT:USDT', 'LTC/USDT:USDT', 'DOGE/USDT:USDT', 
      'OP/USDT:USDT', 'SUI/USDT:USDT', 'TRX/USDT:USDT', 'UNI/USDT:USDT', 
      'XMR/USDT:USDT', 'SAND/USDT:USDT', 'USDC/USDT:USDT', 'MANA/USDT:USDT', 'SUSHI/USDT:USDT', 'NEO/USDT:USDT', 
      'XTZ/USDT:USDT', 'THETA/USDT:USDT', 'PEOPLE/USDT:USDT', 'LRC/USDT:USDT', 'OMG/USDT:USDT', 
      'NEAR/USDT:USDT', 'DASH/USDT:USDT', 'BNB/USDT:USDT', 'BCH/USDT:USDT', 'DOT/USDT:USDT', 'SHIB/USDT:USDT', 
      'ARB/USDT:USDT', 'ADA/USDT:USDT', 'APT/USDT:USDT', 'EOS/USDT:USDT', 'GMT/USDT:USDT', 'FIL/USDT:USDT', 'DYDX/USDT:USDT', 
      'ATOM/USDT:USDT', 'APE/USDT:USDT', 'CRV/USDT:USDT', 'GALA/USDT:USDT', 'AAVE/USDT:USDT', 'AXS/USDT:USDT', 
      'COMP/USDT:USDT', 'ICP/USDT:USDT', 'ALGO/USDT:USDT', 'GRT/USDT:USDT', '1INCH/USDT:USDT', 'CHZ/USDT:USDT', 
      'KNC/USDT:USDT', 'ZIL/USDT:USDT', 'AR/USDT:USDT', 'BSV/USDT:USDT', ]
  
deepspace:
  bybit_subaccount1: &bybit_subaccount1
    apikey: xyz
    apisecret: zyx
  binance_subaccount1: &binance_subaccount1
    apikey: xyz
    apisecret: xyz
  binance_subaccount2: &binance_subaccount2
    apikey: xyz
    apisecret: xyz
  okx_subaccount1: &okx_subaccount1
    apikey: zyx
    apisecret: xyz
  
  funding_payments:
    bybit:
      <<: *funding_payments
      helper: bybithelper.py
      subaccount1: *bybit_subaccount1
    binance:
      <<: *funding_payments
      helper: binancehelper.py
      subaccount1: *binance_subaccount1
      subaccount2: *binance_subaccount2
    okx:
      <<: *funding_payments
      helper: okxhelper.py
      subaccount1: *okx_subaccount1

  balances:    
    function: balance.py
    scheduler: [continuous,external,5 4 * * * ]
    bybit:
      <<: *balances
      helper: bybithelper.py
      subaccount1: *bybit_subaccount1
    binance:
      <<: *balances
      helper: binancehelper.py
      subaccount1: *binance_subaccount1
      subaccount2: *binance_subaccount2
    okx:
      <<: *balances
      helper: okxhelper.py
      subaccount1: *okx_subaccount1

highsky:  
  funding_payments:
    bybit:
      <<: *funding_payments
      helper: bybithelper.py
      subaccount1: *bybit_subaccount1
    binance:
      <<: *funding_payments
      helper: binancehelper.py
      subaccount1: *binance_subaccount1
      subaccount2: *binance_subaccount2
    okx:
      <<: *funding_payments
      helper: okxhelper.py
      subaccount1: *okx_subaccount1

  balances:    
    function: balance.py
    scheduler: [continuous,external,5 4 * * * ]
    bybit:
      <<: *balances
      helper: bybithelper.py
      subaccount1: *bybit_subaccount1
    binance:
      <<: *balances
      helper: binancehelper.py
      subaccount1: *binance_subaccount1
      subaccount2: *binance_subaccount2
    okx:
      <<: *balances
      helper: okxhelper.py
      subaccount1: *okx_subaccount1
