mongo_host: 127.0.0.1
mongo_db: 'active_digital'
mongo_port: 27017

dask:
  back_off: 100
  memory: '1GB'
  workers: 1
  threadPoolsPerWorker: 1
  threadsPerPool: 2

logging:
  max_size: 100 # in KB
  max_date: 5 # in days

ccxt:
  binance:
    rateLimit: 30
    timeout: 1000
    retry: 3
  okx:
    rateLimit: 30
    timeout: 1000
    retry: 3
  bybit:
    rateLimit: 30
    timeout: 1000
  coinbase:
    rateLimit: 30
    timeout: 1000
    retry: 3

liquidation:
  threshold: 
    binance: 1.7
    binance_pm: 1.7
    okx: 0.95
    bybit: 0.75
  scalar:
    binance: 1
    binance_pm: 1
    okx: 0.125
    bybit: -1

funding_payments: &funding_payments
  function: funding_payments.py
  scheduler: [continuous,external,5 4 * * *]
  base_ccy: USD

balances: &balances
  function: balance.py
  scheduler: [continuous,external,5 4 * * * ]
  base_ccy: USDT
  store_type: timeseries

symbols:
  symbols_1: &symbols_1 ['BTC', 'ETH', 'USDT', 'XRP', 'BNB', 'DOGE', 'SOL', 'LTC', 'BCH', 'DOT', 'ARB', 'ADA', 'OP', 
    'SUI', 'APT', 'EOS', 'ECT', 'FIL', 'DYDX', 'ATOM', 'APE', 'CRV', 'TRX', 'RUNE', 'UNI', 'GALA', 'NEAR', 
    '1000PEPE', 'PEPE', 'XMR', 'SAND', 'AAVE', 'USDC', 'AXS', 'COMP', 'GMT', 'ICP', 'MANA', 'ALGO', 'SHIB', 'SUSHI', 
    'GRT', '1INCH', 'CHZ', 'NEO', 'KNC', 'XTZ', 'THETA', 'DASH', 'PEOPLE', 'LRC', 'ZIL', 'OMG', 'ROSE', 'AR', 'COTI', 'ICX', ]

  symbols_2: &symbols_2 ['BTC/USDT', 'ETH/USDT', 'XRP/USDT', 'BNB/USDT', 'DOGE/USDT', 'SOL/USDT', 'LTC/USDT', 
    'BCH/USDT', 'DOT/USDT', 'ARB/USDT', 'ADA/USDT', 'OP/USDT', 'SUI/USDT', 'APT/USDT', 'EOS/USDT', 'ECT/USDT', 
    'FIL/USDT', 'DYDX/USDT', 'ATOM/USDT', 'APE/USDT', 'CRV/USDT', 'TRX/USDT', 'RUNE/USDT', 'UNI/USDT', 'GALA/USDT', 
    'NEAR/USDT', '1000PEPE/USDT', 'PEPE/USDT', 'XMR/USDT', 'SAND/USDT', 'AAVE/USDT', 'USDC/USDT', 'AXS/USDT',
    'COMP/USDT', 'GMT/USDT', 'ICP/USDT', 'MANA/USDT', 'ALGO/USDT', 'SHIB/USDT', 'SUSHI/USDT', 'GRT/USDT', '1INCH/USDT', 
    'CHZ/USDT', 'NEO/USDT', 'KNC/USDT', 'XTZ/USDT', 'THETA/USDT', 'DASH/USDT', 'PEOPLE/USDT', 'LRC/USDT', 'ZIL/USDT', 
    'OMG/USDT', 'ROSE/USDT', 'AR/USDT', 'COTI/USDT', 'ICX/USDT', 'LINK/USDT']

  symbols_3: &symbols_3 ['BTC/USDT:USDT', 'ETH/USDT:USDT', 'XRP/USDT:USDT', 'BNB/USDT:USDT', 'DOGE/USDT:USDT', 
    'SOL/USDT:USDT', 'LTC/USDT:USDT', 'BCH/USDT:USDT', 'DOT/USDT:USDT', 'ARB/USDT:USDT', 'ADA/USDT:USDT', 'OP/USDT:USDT', 
    'SUI/USDT:USDT', 'APT/USDT:USDT', 'EOS/USDT:USDT', 'ECT/USDT:USDT', 'FIL/USDT:USDT', 'DYDX/USDT:USDT', 'ATOM/USDT:USDT', 
    'APE/USDT:USDT', 'CRV/USDT:USDT', 'TRX/USDT:USDT', 'RUNE/USDT:USDT', 'UNI/USDT:USDT', 'GALA/USDT:USDT', 'NEAR/USDT:USDT', 
    '1000PEPE/USDT:USDT', 'PEPE/USDT:USDT', 'XMR/USDT:USDT', 'SAND/USDT:USDT', 'AAVE/USDT:USDT', 'USDC/USDT:USDT', 
    'AXS/USDT:USDT', 'COMP/USDT:USDT', 'GMT/USDT:USDT', 'ICP/USDT:USDT', 'MANA/USDT:USDT', 'ALGO/USDT:USDT', 'SHIB/USDT:USDT', 
    'SUSHI/USDT:USDT', 'GRT/USDT:USDT', '1INCH/USDT:USDT', 'CHZ/USDT:USDT', 'NEO/USDT:USDT', 'KNC/USDT:USDT', 'XTZ/USDT:USDT', 
    'THETA/USDT:USDT', 'DASH/USDT:USDT', 'PEOPLE/USDT:USDT', 'LRC/USDT:USDT', 'ZIL/USDT:USDT', 'OMG/USDT:USDT', 
    'ROSE/USDT:USDT', 'AR/USDT:USDT', 'COTI/USDT:USDT', 'ICX/USDT:USDT', 'LINK/USDT:USDT',]

  symbols_4: &symbols_4 ['BTCUSD_PERP', 'ETHUSD_PERP', 'USDTUSD_PERP', 'XRPUSD_PERP', 'BNBUSD_PERP', 'DOGEUSD_PERP', 
    'SOLUSD_PERP', 'LTCUSD_PERP', 'BCHUSD_PERP', 'DOTUSD_PERP', 'ARBUSD_PERP', 'ADAUSD_PERP', 'OPUSD_PERP', 'SUIUSD_PERP', 
    'APTUSD_PERP', 'EOSUSD_PERP', 'ECTUSD_PERP', 'FILUSD_PERP', 'DYDXUSD_PERP', 'ATOMUSD_PERP', 'APEUSD_PERP', 
    'CRVUSD_PERP', 'TRXUSD_PERP', 'RUNEUSD_PERP', 'UNIUSD_PERP', 'GALAUSD_PERP', 'NEARUSD_PERP', '1000PEPEUSD_PERP', 
    'PEPEUSD_PERP', 'XMRUSD_PERP', 'SANDUSD_PERP', 'AAVEUSD_PERP', 'USDCUSD_PERP', 'AXSUSD_PERP', 'COMPUSD_PERP', 
    'GMTUSD_PERP', 'ICPUSD_PERP', 'MANAUSD_PERP', 'ALGOUSD_PERP', 'SHIBUSD_PERP', 'SUSHIUSD_PERP', 'GRTUSD_PERP', 
    '1INCHUSD_PERP', 'CHZUSD_PERP', 'NEOUSD_PERP', 'KNCUSD_PERP', 'XTZUSD_PERP', 'THETAUSD_PERP', 'DASHUSD_PERP', 
    'PEOPLEUSD_PERP', 'LRCUSD_PERP', 'ZILUSD_PERP', 'OMGUSD_PERP', 'ROSEUSD_PERP', 'ARUSD_PERP', 'COTIUSD_PERP', 'ICXUSD_PERP', ]

  symbols_5: &symbols_5 ['BTC/USD:BTC', 'ETH/USD:ETH', 'XRP/USD:XRP', 'BNB/USD:BNB', 'DOGE/USD:DOGE', 'SOL/USD:SOL', 
    'LTC/USD:LTC', 'BCH/USD:BCH', 'DOT/USD:DOT', 'ARB/USD:ARB', 'ADA/USD:ADA', 'OP/USD:OP', 'SUI/USD:SUI', 
    'APT/USD:APT', 'EOS/USD:EOS', 'ECT/USD:ECT', 'FIL/USD:FIL', 'DYDX/USD:DYDX', 'ATOM/USD:ATOM', 'APE/USD:APE', 
    'CRV/USD:CRV', 'TRX/USD:TRX', 'RUNE/USD:RUNE', 'UNI/USD:UNI', 'GALA/USD:GALA', 'NEAR/USD:NEAR', '1000PEPE/USD:1000PEPE', 
    'PEPE/USD:PEPE', 'XMR/USD:XMR', 'SAND/USD:SAND', 'AAVE/USD:AAVE', 'USDC/USD:USDC', 'AXS/USD:AXS', 'COMP/USD:COMP', 
    'GMT/USD:GMT', 'ICP/USD:ICP', 'MANA/USD:MANA', 'ALGO/USD:ALGO', 'SHIB/USD:SHIB', 'SUSHI/USD:SUSHI', 'GRT/USD:GRT', 
    '1INCH/USD:1INCH', 'CHZ/USD:CHZ', 'NEO/USD:NEO', 'KNC/USD:KNC', 'XTZ/USD:XTZ', 'THETA/USD:THETA', 'DASH/USD:DASH', 
    'PEOPLE/USD:PEOPLE', 'LRC/USD:LRC', 'ZIL/USD:ZIL', 'OMG/USD:OMG', 'ROSE/USD:ROSE', 'AR/USD:AR', 'COTI/USD:COTI', 
    'ICX/USD:ICX', 'LINK/USD:LINK']

instruments:
  store_type: snapshot

positions:
  store_type: timeseries
  margin_mode: non_portfolio
  bybit_coins: ["BTC", "ETH", "XRP", "ADA", "DOT", "LTC", "EOS", "MANA", "USDT", "USDC", ]
  cross_margin_ratio_threshold:
    binance: 1.05
    okx: 300

tickers:
  symbols: *symbols_2
  store_type: timeseries

index_prices:
  symbols: 
    okx: *symbols_2
    binance: *symbols_2
    bybit: *symbols_2
  store_type: timeseries

leverages:
  store_type: timeseries

transactions:
  store_type: timeseries
  fetch_type: time # time, id
  time_slack: 600000 # in ms

fills:
  store_type: timeseries
  fetch_type: time # time, id

  symbols:
    binance: *symbols_2 # ['BTCUSDT',]
    okx: *symbols_2 # ['BTC-USDT-SWAP',]
    bybit: *symbols_2

mark_prices:
  store_type: timeseries
  binance: ["BTCUSDT", ]
  okx: ["BTC-USDT-SWAP", ]
  bybit: ["BTCUSDT", ]

bid_ask:
  spot: *symbols_2
  perp: *symbols_3

borrow_rates:
  period: 
    binance: daily # yearly, daily or interval
    okx: yearly # yearly, daily or interval
    bybit: daily # yearly, daily or interval

  codes: *symbols_1

funding_rates:
  bybit:
    helper: bybithelper.py
    instruments:
      ["BTC.USDT.PERP","ETH.USDT.PERP"]
  binance:
    helper: helper.py
    instruments:  
      ["BTC.USDT.PERP","ETH.USDT.PERP"]
    valid: valid_from # valid_to, valid_from
  okx:
    helper: okxhelper.py
    instruments:
      ["BTC.USDT.PERP","ETH.USDT.PERP"]
    valid: valid_to

  period: interval # yearly, daily or interval

  symbols:
    binance_usdt: *symbols_3
    binance_usd: *symbols_5
    okx_usdt: *symbols_3
    okx_usd: *symbols_5
    bybit_usdt: *symbols_3
    bybit_usd: *symbols_5

exchanges: ["binance", "okx", "bybit", ]

clients:
  rundmc:
    split_positions: True
    binance_subaccount4: &binance_subaccount4
      apikey: xyz
      apisecret: xyz
      margin_mode: non_portfolio
      hedged_exclusion_positive: {'USDT': 0}
      hedged_exclusion_negative: {'USDT': 0}
    binance_subaccount6: &binance_subaccount6
      apikey: xyz
      apisecret: xyz
      margin_mode: non_portfolio
      hedged_exclusion_positive: {'USDT': 0}
      hedged_exclusion_negative: {'USDT': 0}
    binance_subaccountpm1: &binance_subaccountpm1
      apikey: xyz
      apisecret: xyz
      margin_mode: portfolio
      hedged_exclusion_negative: {'USDT': 0}
      hedged_exclusion_positive: {'USDT': 0}
    okx_subaccount1: &okx_subaccount1
      apikey: zyx
      apisecret: xyz
      margin_mode: non_portfolio
      hedged_exclusion_positive: {'USDT': 0}
      hedged_exclusion_negative: {'USDT': 0}

    funding_payments:
      binance:
        <<: *funding_payments
        helper: helper.py
        subaccount4: *binance_subaccount4
        subaccount6: *binance_subaccount6
        subbinancepm1: *binance_subaccountpm1
      okx:
        <<: *funding_payments
        helper: okxhelper.py
        subaccount1: *okx_subaccount1

    balances:
      function: balance.py
      scheduler: [continuous,external,5 4 * * * ]
      binance:
        <<: *balances
        helper: helper.py
        subaccount4: *binance_subaccount4
        subaccount6: *binance_subaccount6
        subbinancepm1: *binance_subaccountpm1
      okx:
        <<: *balances
        helper: okxhelper.py
        subaccount1: *okx_subaccount1

  besttrader:
    split_positions: True
    okx_sub1ap: &okx_sub1ap
      apikey: zyx
      apisecret: xyz
      margin_mode: non_portfolio
      hedged_exclusion_positive: {'USDT': 0}
      hedged_exclusion_negative: {'USDT': 0}
    okx_sub1aa: &okx_sub1aa
      apikey: zyx
      apisecret: xyz
      margin_mode: non_portfolio
      hedged_exclusion_positive: {'USDT': 0}
      hedged_exclusion_negative: {'USDT': 0}
    bybit_sub1: &bybit_sub1
      margin_mode: non_portfolio
      apikey: zyx
      apisecret: xyz
      hedged_exclusion_positive: {'USDT': 0}
      hedged_exclusion_negative: {'USDT': 0}
    bybit_sub4: &bybit_sub4
      margin_mode: non_portfolio
      apikey: zyx
      apisecret: xyz
      hedged_exclusion_positive: {'USDT': 0}
      hedged_exclusion_negative: {'USDT': 0}

    funding_payments:
      okx:
        <<: *funding_payments
        helper: okxhelper.py
        sub1ap: *okx_sub1ap
        sub2aa: *okx_sub1aa
      bybit:
        <<: *funding_payments
        helper: helper.py
        sub1: *bybit_sub1
        sub4: *bybit_sub4

    balances:
      function: balance.py
      scheduler: [continuous,external,5 4 * * * ]
      okx:
        <<: *balances
        helper: okxhelper.py
        sub1ap: *okx_sub1ap
        sub2aa: *okx_sub1aa

  wizardly:
    split_positions: True
    okx_submn: &okx_submn
      apikey: zyx
      apisecret: xyz
      margin_mode: non_portfolio
      hedged_exclusion_positive: {'USDT': 0}
      hedged_exclusion_negative: {'USDT': 0}
    binance_submn: &binance_submn
      apikey: xyz
      apisecret: xyz
      margin_mode: portfolio
      hedged_exclusion_positive: {'USDT': 0}
      hedged_exclusion_negative: {'USDT': 0}  

    funding_payments:
      okx:
        <<: *funding_payments
        base_ccy: USDT
        helper: okxhelper.py
        submn: *okx_submn
      binance:
        <<: *funding_payments
        base_ccy: USDT
        helper: helper.py
        submn: *binance_submn        

    balances:
      function: balance.py
      scheduler: [continuous,external,5 4 * * * ]
      okx:
        <<: *balances
        helper: okxhelper.py
        submn: *okx_submn
      binance:
        <<: *balances
        helper: helper.py
        submn: *binance_submn
        
  jess:
    split_positions: True
    okx_subandyactivedigital: &okx_subandyactivedigital
      apikey: zyx
      apisecret: xyz
      margin_mode: non_portfolio
      hedged_exclusion_positive: {'USDT': 0}
      hedged_exclusion_negative: {'USDT': 0}
    okx_subandypants: &okx_subandypants
      apikey: zyx
      apisecret: xyz
      margin_mode: non_portfolio
      hedged_exclusion_positive: {'USDT': 0}
      hedged_exclusion_negative: {'USDT': 0}
    okx_subjessetf: &okx_subjessetf
      apikey: zyx
      apisecret: xyz
      margin_mode: non_portfolio
      hedged_exclusion_positive: {'USDT': 0}
      hedged_exclusion_negative: {'USDT': 0}
    okx_subadtest2: &okx_subadtest2
      apikey: zyx
      apisecret: xyz
      margin_mode: non_portfolio
      hedged_exclusion_positive: {'USDT': 0}
      hedged_exclusion_negative: {'USDT': 0}

    funding_payments:
      okx:
        <<: *funding_payments
        helper: okxhelper.py
        subandyactivedigital: *okx_subandyactivedigital
        subandypants: *okx_subandypants
        subjessetf: *okx_subjessetf
        subadtest2: *okx_subadtest2

    balances:
      function: balance.py
      scheduler: [continuous,external,5 4 * * * ]
      okx:
        <<: *balances
        helper: okxhelper.py
        subandyactivedigital: *okx_subandyactivedigital
        subandypants: *okx_subandypants
        subjessetf: *okx_subjessetf
        subadtest2: *okx_subadtest2

  blackburn:
    split_positions: True
    binance_submn1: &binance_submn1
      apikey: xyz
      apisecret: xyz
      margin_mode: portfolio
      hedged_exclusion_positive: {'USDT': 0}
      hedged_exclusion_negative: {'USDT': 0}
      
    funding_payments:
      binance:
        <<: *funding_payments
        helper: helper.py
        submn1: *binance_submn1

    balances:
      function: balance.py
      scheduler: [continuous,external,5 4 * * * ]
      binance:
        <<: *balances
        helper: helper.py
        submn1: *binance_submn1
